name: fura24.kz
description: "IT project fura24.kz - Mobile Application."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  dio: ^5.4.0
  go_router: ^14.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  timeago: ^3.6.0
  flutter_screenutil: ^5.9.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_riverpod: ^2.4.9
  flutter_slidable: ^3.1.0
  collection: ^1.18.0
  easy_localization: ^3.0.1
  connectivity_plus: ^5.0.2
  image: ^4.0.20
  image_picker: ^0.8.5+3
  country_code_picker: ^3.1.3 
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.3.3
  modal_bottom_sheet: ^2.1.2
  mask_text_input_formatter: ^2.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^17.2.2
  package_info_plus: ^8.0.2
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/svg/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
